version: '3.1'

services:
  db:
    image: 'mysql'
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: xx11223
    ports:
      - '3306:3306'
    volumes:
      - './dbdata/mysql:/var/lib/mysql'
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - '8081:80'

  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./dbdata/cassandra:/var/lib/cassandra
