# create users
POST http://localhost:8080/users
Content-Type: application/json

{
  "first_name": "Javad",
  "last_name": "Rajabzade",
  "email": "dev@javad.tech"
}

###

# get users
GET http://localhost:8080/users/1
Accept: application/json

###

# update users
PUT http://localhost:8080/users/1
Content-Type: application/json

{

}