# create users
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": 12,
  "first_name": "Javad",
  "last_name": "Rajabzade",
  "email": "dev@javad.tech",
  "date_created": "xxxx-xx-xx"
}

###

# get users
GET http://localhost:8080/users/123
Accept: application/json
