# create users
POST http://localhost:8080/users
Content-Type: application/json

{
  "first_name": "Javad",
  "last_name": "Rajabzade",
  "email": "dev@javad.tech",
  "password": "11223"
}

###

# get users
GET http://localhost:8080/users/1
Accept: application/json

###

# update user
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "first_name": "Ali",
  "last_name": "Asadi",
  "email": "dev@javad.tech"
}

###

# patch user
PATCH http://localhost:8080/users/1
Content-Type: application/json

{
  "last_name": "Rajabzade"
}

###

# delete user
DELETE http://localhost:8080/users/1
Content-Type: application/json

###

# search user
GET http://localhost:8080/internal/users/search?status=active
Content-Type: application/json


